version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mime-types
    versions:
    - 2.1.28
    - 2.1.29
  - dependency-name: random-int
    versions:
    - 2.0.1
